//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Chat.Data.Database
{
	/// <summary>
	/// Database       : chat
	/// Data Source    : tcp://localhost:5432
	/// Server Version : 15.0
	/// </summary>
	public partial class DBContext : LinqToDB.Data.DataConnection
	{
		public ITable<User> Users { get { return this.GetTable<User>(); } }

		partial void InitMappingSchema()
		{
		}

		public DBContext()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DBContext(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DBContext(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public DBContext(DataOptions<DBContext> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="public", Name="users")]
	public partial class User
	{
		[Column("id"), Identity] public int Id { get; set; } // integer
	}
}
