/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MyNotification: typeof import('./src/components/UI/MyNotification/MyNotification.vue')['default']
    PopupWithForm: typeof import('./src/components/PopupWithForm/PopupWithForm.vue')['default']
    Preview: typeof import('./src/components/Tabs/Preview/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
