/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactBlock: typeof import('./src/components/Tabs/Contacts/ContactBlock/ContactBlock.vue')['default']
    GroupPreview: typeof import('./src/components/Tabs/Groups/GroupPreview/GroupPreview.vue')['default']
    MyPopup: typeof import('./src/components/UI/MyPopup/MyPopup.vue')['default']
    Preview: typeof import('./src/components/Tabs/Preview/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/Tabs/SearchBox/SearchBox.vue')['default']
  }
}
