name: build ui

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install packages
      working-directory: ./clientapp
      run: npm install

    - name: check for errors
      working-directory: ./clientapp
      run: npm run typecheck

    - name: build
      working-directory: ./clientapp
      run: npm run build
